# Generated by Django 3.2.5 on 2021-07-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mymodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('uuid', models.CharField(max_length=200)),
                ('modulepassword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='weightdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('uuid', models.CharField(max_length=200)),
            ],
        ),
    ]
