# Generated by Django 3.2.5 on 2021-08-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('linetoken', models.CharField(max_length=200)),
                ('temperature', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='mymodule',
        ),
        migrations.DeleteModel(
            name='weightdata',
        ),
    ]
